name: learn-github-actions-yarn
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
      - run: yarn add bats
      - run: yarn run bats --tap tests/bats/bats-test
